//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FunktionWin.rc
//
#define IDD_FUNKTIONWIN_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       132
#define IDD_FW_INF                      133
#define IDC_DATE                        1001
#define IDC_TIME                        1002
#define ID_PROGRAMM_INFO                32771
#define ID_PROGRAMM_BEENDEN             32772
#define ID_TRANSFORMATIONEN_FISHERZFUNKTION 32773
#define ID_TRANSFORMATIONEN_GAMMA       32774
#define ID_VERTEILUNGSFUNKTIONEN_NORMALVERTEILUNGSFUNKTION 32775
#define ID_VERTEILUNGSFUNKTIONEN_NORMALVERTEILUNGSDICHTEFUNKTION 32776
#define ID_VERTEILUNGSFUNKTIONEN_TFUNKTION 32777
#define ID_VERTEILUNGSFUNKTIONEN_CHIQUADRATFUNKTION 32778
#define ID_VERTEILUNGSFUNKTIONEN_FFUNKTION 32779
#define ID_WAHRSCHEINLICHKEITSFUNKTIONEN_BINOMIALFUNKTION 32780
#define ID_WAHRSCHEINLICHKEITSFUNKTIONEN_POISSONFUNKTION 32781
#define ID_WAHRSCHEINLICHKEITSFUNKTIONEN_GEOMETRISCHEFUNKTION 32782
#define ID_WAHRSCHEINLICHKEITSFUNKTIONEN_HYPERGEOMETRISCHEFUNKTION 32783
#define ID_WAHRSCHEINLICHKEITSFUNKTIONEN_HYPERGEOMETRISCHER4FELDERFISHEREXACTTEST 32784
#define ID_BINOMIALTEST                 32785
#define ID_EPSILON                      32786

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
